[package]
name = "ccfinder-ng"
version = "0.1.0"
edition = "2021"

[build-dependencies]
sha2 = "0.10"
curl = "0.4"
toml = "0.5"
serde = "1"
serde_derive = "1"
wisent = {path = "../wisent"}

[dependencies]
wisent = {path = "../wisent"}
